### ISSUE TITLE
Enhanced Celestials 5.0.2.2 Crash

### ISSUE THREAD

**Issue by Vedvod** [Arcaryx/Cobblemon-Integrations#17]
```
java.lang.NoSuchMethodError: 'net.minecraft.class_6880 corgitaco.enhancedcelestials.lunarevent.LunarForecast.getCurrentEventRaw()'
at knot//com.arcaryx.cobblemonintegrations.enhancedcelestials.EnhancedCelestialsHandler.ECModifySpawns(EnhancedCelestialsHandler.java:32)
at knot//com.cobblemon.mod.common.api.spawning.detail.PokemonSpawnAction.handler$cgg000$cobblemonintegrations$adjustCreateEntity(PokemonSpawnAction.java:528)
at knot//com.cobblemon.mod.common.api.spawning.detail.PokemonSpawnAction.createEntity(PokemonSpawnAction.java)
...
```
It seems that the `getCurrentEventRaw()` function above was [removed two days ago in update 5.0.2.0](https://github.com/CorgiTaco/Enhanced-Celestials/commit/a1eba85aaa2a68b6939d07dd4abff432ed40806c), hence causing the crash. I believe it may have been replaced by `currentLunarEvent()`, but I'm not sure if it's a 100% replacement.

**Comment by CorgiTaco** [comment]
yeah internals did change
